package br.com.alura.leilao.test.support;

public enum Expected_Conditions {
	ALERTISPRESENT,
	ELEMENTSELECTIONSTATETOBE_TRUE,	
	ELEMENTSELECTIONSTATETOBE_FALSE,
	ELEMENTTOBECLICKABLE,
	ELEMENTTOBESELECTED,
	FRAMETOBEAVAILABLEANDSWITCHTOIT,
	INVISIBILITYOFELEMENTLOCATED,
	PRESENCEOFELEMENTLOCATED;
}
